# Container for each version of Terragrunt.

ARG TF_VER=1.3.10
ARG TG_VER

FROM tf:${TF_VER}
ARG TG_VER
RUN	wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VER}/terragrunt_linux_amd64 -O /bin/terragrunt && \
	chmod +x /bin/terragrunt
